version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: gdd/laravel
        container_name: myapp
        restart: unless-stopped
        command: composer install && php artisan migrate && npm install && npm run dev
        tty: true
        environment:
            SERVICE_NAME: myapp
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - mynet

    nginx:
        container_name: lara-nginx
        image: nginx:alpine
        working_dir: /var/www/html
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        networks:
            - mynet

    db:
        image: mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: vid
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - mynet

    redis:
        image: redis
        restart: always
        tty: true
        ports:
            - "6379:6379"
        networks:
            - mynet

#Docker Networks
networks:
    mynet:
        driver: bridge
#Volumes
volumes:
    mysql:
        driver: local
